version: "3.9"
services:
  app_gateway:
    image: backend/app_gateway:1.0
    container_name: app_gateway
    restart: on-failure    
    env_file: ./.env
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE=prod       
    ports:      
      - 8080:9088
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true